name: Destroy Preview Namespace

on: 
  pull_request: 
    types:
      - closed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Delete namespace
      uses: okteto/destroy-preview@master
      env:
       OKTETO_TOKEN: ${ secrets.OKTETO_TOKEN}
       OKTETO_URL: https://staging.okteto.dev
      with:
        name: pr-${{ github.event.number }}-jlopezbarb
